# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    java -jar C:\Test\BDDetect\detect-10.3.0.jar --blackduck.url=https://sca.demo.blackduck.com --blackduck.trust.cert=true --blackduck.api.token=NmUyNjJlOTgtZWIyYi00YWY3LTg1YTYtMWQ0NDQzODNkNTk2Ojc2ZTdiYjE5LWRmZDYtNDQ2Ny05YmFlLTgwY2RjMGUwZWM4Zg==  --detect.source.path=$(System.DefaultWorkingDirectory) --detect.project.name=InsecBank --detect.project.version.name=1.0 --detect.cleanup=false --blackduck.offline.mode=false
  displayName: 'Run SCA Analysis'
